/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from "./MockERC20";
export type { RoleManager } from "./RoleManager";
export * as factories from "./factories";
export { MockERC20__factory } from "./factories/MockERC20__factory";
export { RoleManager__factory } from "./factories/RoleManager__factory";
